name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # To deploy the client side, we'll push only the `client` directory of
      # this repository to the `github-pages-live` branch.
      - name: Push the client/ folder to the github-pages-live branch
        uses: s0/git-publish-subdir-action@v2.4.0
        with:
          REPO: self
          BRANCH: github-pages-live
          FOLDER: client
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOYMENT_KEY }}
