name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # To deploy the client side, we'll push only the `client` directory of
      # this repository to the `github-pages-live` branch.
      - uses: nxtlvlsoftware/git-subtree-action@1
        with:
          repo: helloworld12321/aws-wildrydes-tutorial
          branch: github-pages-live
          path: client
          deploy_key: ${{ secrets.GH_DEPLOYMENT_KEY }}
          force: true
