name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # To deploy the client side, we'll push only the `client` directory of
      # this repository to the `github-pages-live` branch.
      - name: Push the client/ folder to the github-pages-live branch
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: github-pages-live
          FOLDER: client
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOYMENT_TOKEN }}
  
  deploy-request-unicorn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the AWS CLI
        run: sudo apt-get update && sudo apt-get install awscli
      - name: Add ~/.aws/credentials and ~/.aws/config
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region us-east-1
      - name: Build the ZIP file
        run: cp lambda/requestUnicorn.js index.js && zip ../requestUnicorn.zip index.js
      - name: Deploy the ZIP file to AWS lambda
        run: |
          aws lambda update-function-code \
            --function-name RequestUnicorn \
            --zip-file fileb://requestUnicorn.zip
