name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # To deploy the client side, we'll push only the `client` directory of
      # this repository to the `github-pages-live` branch.
      - name: Push the client/ folder to the github-pages-live branch
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: github-pages-live
          FOLDER: client
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOYMENT_TOKEN }}
  
  # Adapted from https://blog.jakoblind.no/aws-lambda-github-actions/
  deploy-request-unicorn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy the function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: RequestUnicorn
          source: lamdba/requestUnicorn.js
